baseurl = "https://domen.ipavec.net/"
languageCode = "en-us"

theme = "hugo-theme-bootstrap4-blog"
pygmentsuseclasses = true

disqusShortname = "domenipavecsblog"
googleAnalytics = "UA-6928536-7"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true

preservetaxonomynames = true

copyright = '<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Web contents</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="https://domen.ipavec.net" property="cc:attributionName" rel="cc:attributionURL">Domen Ipavec</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.'

[taxonomies]
category = "categories"
tag = "tags"

[Params]
Author = "Domen Ipavec"

[social]
twitter = "DomenIpavec"

[permalinks]
post = "/:filename"

[Params.sidebar]
about = '''
<img src="/images/domen.jpg.s300.jpg" class="img-fluid rounded-circle">
<h3>Domen Ipavec</h3>
<a href="https://github.com/matematik7" title="Github">
	<i class="fa fa-github fa-fw fa-lg" aria-hidden="true"></i> matematik7
</a><br>
<a href="mailto:do&#109;en%2e&#105;&#112;%61%76e%63@%67%6dai%6c.co%6d">
	<i class="fa fa-envelope fa-lg fa-fw" aria-hidden="true"></i> d&#111;&#109;&#101;&#110;.&#105;pa&#118;&#101;c@&#103;&#109;ai&#108;&#46;&#99;o&#109;
</a>
'''

[Languages]
[Languages.en]
weight = 1
title = "Domen Ipavec's Blog"

[[Languages.en.menu.main]]
url = "/en/"
name = "Home page"
weight = 0

[Languages.sl]
weight = 2
title = 'Domen Ipavec'
copyright = '<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Spletne vsebine</span> <a xmlns:cc="http://creativecommons.org/ns#" href="https://domen.ipavec.net" property="cc:attributionName" rel="cc:attributionURL">Domna Ipavca</a> so pod <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.'

[[Languages.sl.menu.main]]
url = "/sl/"
name = "Domača stran"
weight = 0

[markup.goldmark.renderer]
unsafe = true
